#.travis.yml

language: node_js
node_js:
  - "6.10.1"

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng test
  - ng build --prod --aot
  - npm run precache

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change